Added Online Banking PL (P24) component
Adyen/adyen-web pull request #1721
Opened 2022-09-06 08:04 UTC by jobsturm

## Summary
This adds support for Online Banking PL (P24)

2022-09-08 13:15 UTC, ribeiroguilherme approved these changes

2022-09-08 13:15 UTC, ribeiroguilherme commented on packages/playground/src/pages/IssuerLists/IssuerLists.js
> -            currency: 'EUR'
We can leave 'EUR' as default - there is no point to change it

2022-09-12 13:46 UTC, ribeiroguilherme requested changes

2022-09-12 13:46 UTC, ribeiroguilherme commented on packages/lib/src/components/P24/index.ts
> +class P24Element extends IssuerListContainer {
Better to name the payment method to `OnlineBankingPL`, same as we do with the other online banking payment methods (`OnlineBankingCZ`, `OnlineBankingSK`..).  Also rename the folder that keeps it.

2022-09-12 13:46 UTC, ribeiroguilherme commented on packages/lib/src/components/P24/index.ts
> +    public static type = 'dotpay';
Are we sure that tx variant is `dotpay` ? It seems that the ticket description mentions `onlineBanking_PL`

2022-09-12 13:46 UTC, ribeiroguilherme commented on packages/playground/src/pages/IssuerLists/IssuerLists.js
> +    window.dotpay = checkout.create('p24').mount('.p24-field');
This variable name conflicts with the one on line 49.

2022-09-13 07:53 UTC, ribeiroguilherme submitted a review, later dismissed

2022-09-13 07:53 UTC, ribeiroguilherme commented on packages/lib/src/components/index.ts
> +    p24: P24,
This mapping should be updated as well to use `onlineBanking_PL` key

2022-09-19 14:47 UTC, sponglord commented on packages/lib/src/components/UIElement.tsx
> +        console.log(this.props.type || this.constructor['type']);
Can we get rid of this ;-)

2022-09-19 14:59 UTC, sponglord approved these changes

2022-09-19 15:40 UTC, merged