Add parameter to request GPay `assuranceDetails`
Adyen/adyen-web pull request #2132
Opened 2023-05-03 22:58 UTC by mauriciojunior

## Summary

Add parameter to request GPay `assuranceDetails`.

2023-05-05 14:27 UTC, longyulongyu reviewed
Technically your PR looks fine to me. However, could you help me to understand your use case? Thanks!

2023-05-08 14:58 UTC, ribeiroguilherme requested changes

2023-05-08 14:58 UTC, ribeiroguilherme commented on packages/lib/src/components/GooglePay/types.ts
> +    assuranceDetailsRequired?: boolean;
Can you please add the default value to the [GooglePay/defaultProps.ts](https://github.com/Adyen/adyen-web/blob/master/packages/lib/src/components/GooglePay/defaultProps.ts) file ?

2023-05-08 17:03 UTC, ribeiroguilherme approved these changes
Thanks for contributing @mauriciojunior . This change will be available on next release, which likely will take place next week. Cheers

2023-05-08 17:04 UTC, merged