Remove aria-hidden attribute on brand icon
Adyen/adyen-web pull request #2188
Opened 2023-05-24 10:57 UTC by sponglord

## Summary
The brand image in the credit card, visible once a brand has been identified, should have an `alt` tag detailing the card brand, and thus making it readable by screenreaders. 

This was the case _except_  we were also adding an `aria-hidden` attribute, which hid this element from screenreaders.

This has now been fixed. 

## Tested scenarios
`aria-hidden` attribute no longer set on brand or dual-brand icons

**Fixed issue**:  #1691

2023-05-24 16:06 UTC, m1aw approved these changes

2023-05-24 16:15 UTC, m1aw requested changes
1. I had approved but then I went to check and we should also be loading the alt readable text from BRAND_READABLE_NAME_MAP.
2. This actually makes me thing we should make this a prop or function and just leave it in place so it works when we get the brands name form the `paymentMethods` call (so a util function won't work).

We can also do 2. later.

2023-05-25 07:50 UTC, sponglord commented
@m1aw - I don't understand what your comment has to do with removing the `aria-hidden` attributes?
It sounds like what your are proposing belongs in another PR?

2023-05-26 08:41 UTC, m1aw approved these changes

2023-05-30 08:04 UTC, merged